// Sample data for the SL Card Offers UI kit — drawn from the real
// scraped offer set (combank, sampath, seylan, ntb, boc, hnb...).
window.SLCO_DATA = {
  banks: [
    { id: "commercial-bank", name: "Commercial Bank of Ceylon", shortName: "Commercial Bank", offers: 48 },
    { id: "sampath", name: "Sampath Bank", shortName: "Sampath", offers: 31 },
    { id: "seylan", name: "Seylan Bank", shortName: "Seylan", offers: 22 },
    { id: "ntb", name: "Nations Trust Bank", shortName: "NTB", offers: 19 },
    { id: "boc", name: "Bank of Ceylon", shortName: "BOC", offers: 14 },
    { id: "ndb", name: "National Development Bank", shortName: "NDB", offers: 12 },
    { id: "dfcc", name: "DFCC Bank", shortName: "DFCC", offers: 9 },
    { id: "peoples-bank", name: "People's Bank", shortName: "People's Bank", offers: 8 },
    { id: "standard-chartered", name: "Standard Chartered", shortName: "Standard Chartered", offers: 7 },
    { id: "pan-asia-bank", name: "Pan Asia Bank", shortName: "Pan Asia Bank", offers: 6 },
    { id: "union-bank", name: "Union Bank of Colombo", shortName: "Union Bank", offers: 5 },
    { id: "cargills-bank", name: "Cargills Bank", shortName: "Cargills Bank", offers: 4 },
  ],
  categories: [
    { id: "dining", label: "Dining" },
    { id: "fuel", label: "Fuel" },
    { id: "supermarket", label: "Supermarket" },
    { id: "travel", label: "Travel" },
    { id: "online", label: "Online" },
    { id: "installment", label: "Installment" },
    { id: "cashback", label: "Cashback" },
    { id: "bogo", label: "BOGO" },
    { id: "other", label: "Other" },
  ],
  offers: [
    {
      id: "combank-courtyard-marriott", bankId: "commercial-bank", bankName: "Commercial Bank", category: "dining",
      merchant: "Courtyard by Marriott Colombo",
      title: "Up to 15% off at Courtyard by Marriott Colombo",
      description: "15% off lunch, 10% off high tea (weekends only), 10% off dinner buffet (daily except blackout dates) with ComBank Credit Cards. Blackout June 21, 2026.",
      validUntil: "Jun 30, 2026", lastChecked: "Jun 10, 2026", expiringSoon: true,
      sourceUrl: "https://www.combank.lk", cardName: "Commercial Bank Credit Cards", location: "Colombo",
    },
    {
      id: "combank-srilankan", bankId: "commercial-bank", bankName: "Commercial Bank", category: "travel",
      merchant: "SriLankan Airlines",
      title: "Travel offers with SriLankan Airlines",
      description: "Fly to your favourite destination with SriLankan Airlines using ComBank Credit Cards. Special fares and instalment plans available.",
      validUntil: "Jul 31, 2026", lastChecked: "Jun 09, 2026", expiringSoon: false,
      sourceUrl: "https://www.combank.lk", cardName: "Commercial Bank Credit Cards", location: "Sri Lanka",
    },
    {
      id: "combank-visa-thursday", bankId: "commercial-bank", bankName: "Commercial Bank", category: "dining",
      merchant: "Selected restaurants",
      title: "Up to 25% off at selected restaurants — Visa Thursdays",
      description: "Treat yourself with amazing ComBank Visa Card dining offers every Thursday. Up to 25% discount at selected restaurants island-wide.",
      validUntil: "Jul 31, 2026", lastChecked: "Jun 10, 2026", expiringSoon: false,
      sourceUrl: "https://www.combank.lk", cardName: "ComBank Visa Cards", location: "Sri Lanka",
    },
    {
      id: "sampath-keells", bankId: "sampath", bankName: "Sampath", category: "supermarket",
      merchant: "Keells",
      title: "10% off your grocery bill at Keells",
      description: "Enjoy 10% off at all Keells outlets when you pay with your Sampath Bank Credit Card. Minimum spend Rs. 5,000 applies.",
      validUntil: "Aug 15, 2026", lastChecked: "Jun 12, 2026", expiringSoon: false,
      sourceUrl: "https://www.sampath.lk", cardName: "Sampath Credit Cards", location: "Island-wide",
    },
    {
      id: "sampath-fuel", bankId: "sampath", bankName: "Sampath", category: "fuel",
      merchant: "IOC fuel stations",
      title: "5% cashback on fuel at IOC stations",
      description: "Earn 5% cashback (up to Rs. 1,000/month) on fuel purchases at participating Lanka IOC stations with Sampath Credit Cards.",
      validUntil: "Jun 22, 2026", lastChecked: "Jun 12, 2026", expiringSoon: true,
      sourceUrl: "https://www.sampath.lk", cardName: "Sampath Credit Cards", location: "Island-wide",
    },
    {
      id: "seylan-cinnamon", bankId: "seylan", bankName: "Seylan", category: "dining",
      merchant: "Cinnamon Grand Colombo",
      title: "20% off dining at Cinnamon Grand Colombo",
      description: "20% off à la carte and buffet dining at selected Cinnamon Grand restaurants with Seylan Credit Cards. Maximum 6 guests per card.",
      validUntil: "Sep 30, 2026", lastChecked: "Jun 12, 2026", expiringSoon: false,
      sourceUrl: "https://www.seylan.lk", cardName: "Seylan Credit Cards", location: "Colombo",
    },
    {
      id: "ntb-amex-online", bankId: "ntb", bankName: "NTB", category: "online",
      merchant: "Daraz",
      title: "Up to Rs. 3,000 off on Daraz with Amex",
      description: "Get up to Rs. 3,000 instant discount on Daraz purchases above Rs. 15,000 with your Nations Trust American Express Card.",
      validUntil: "Jul 15, 2026", lastChecked: "Jun 10, 2026", expiringSoon: false,
      sourceUrl: "https://www.nationstrust.com", cardName: "NTB American Express", location: "Online",
    },
    {
      id: "boc-installment", bankId: "boc", bankName: "BOC", category: "installment",
      merchant: "Singer & Abans",
      title: "0% interest for 24 months on electronics",
      description: "Convert purchases at Singer and Abans into 0% instalment plans for up to 24 months with BOC Credit Cards.",
      validUntil: "Dec 31, 2026", lastChecked: "Jun 11, 2026", expiringSoon: false,
      sourceUrl: "https://www.boc.lk", cardName: "BOC Credit Cards", location: "Island-wide",
    },
    {
      id: "ndb-bogo-movie", bankId: "ndb", bankName: "NDB", category: "bogo",
      merchant: "Scope Cinemas",
      title: "Buy one get one free on movie tickets",
      description: "Enjoy buy-one-get-one-free on Scope Cinemas tickets every weekend with NDB Credit Cards. Valid for standard seats only.",
      validUntil: "Jun 20, 2026", lastChecked: "Jun 12, 2026", expiringSoon: true,
      sourceUrl: "https://www.ndbbank.com", cardName: "NDB Credit Cards", location: "Colombo",
    },
  ],
};
